### ISSUE TITLE
Add React Backend

### ISSUE THREAD

**Issue by Lucaslah** [CSSUDII/public#1]
# React Backend

## TODO:

- [x] Get started on backend
- [ ] Commit backend
- [ ] GET requests for backend (user)
- [ ] Index Page
- [ ] POST requests for user signup
- [ ] GET requests for Auth token
- [ ] User Login Page

**Comment by Lucaslah** [comment]
Ill commit the base code tomorrow.

**Comment by Lucaslah** [comment]
I’ve stopped working on this for now, when I have time again I’ll start work on this.
